name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id: changed-files
        run: |
          echo "files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Claude Code Review
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in ${{ steps.changed-files.outputs.files }}; do
            if [[ $file =~ \.(py|js|java|cpp|go)$ ]]; then
              content=$(cat $file)
              review=$(curl https://api.anthropic.com/v1/messages \
                -H "x-api-key: $ANTHROPIC_API_KEY" \
                -H "content-type: application/json" \
                -d '{
                  "model": "claude-3-sonnet-20240229",
                  "max_tokens": 1000,
                  "messages": [{
                    "role": "user", 
                    "content": "Please review this code and suggest improvements:\n\n'"$content"'"
                  }]
                }' | jq -r '.content[0].text')
              
              gh pr comment ${{ github.event.pull_request.number }} --body "Review for $file:\n$review"
            fi
          done
